[package]
name = "rs_box"
version = "0.0.10"
description = "rust develop box"
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
documentation = "https://github.com/george012/rs_box"
homepage = "https://github.com/george012/rs_box"
repository = "https://github.com/george012/rs_box"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4.38"
fern = "^0.6.2"
fltk = { version = "^1.4.29", features = ["fltk-bundled"] }
fltk-table = "^0.1.8"
lazy_static = "^1.4"
log = "^0.4.21"
log4rs = "^1.3.0"
toml = "^0.8.12"
