[package]
name = "rs_box"
version = "0.0.12"
description = "rust develop box"
edition = "2021"
readme = "README.md"
license-file = "LICENSE"
documentation = "https://github.com/george012/rs_box"
homepage = "https://github.com/george012/rs_box"
repository = "https://github.com/george012/rs_box"
keywords = [
    "rust_box",
    "rustbox",
    "rust-box",
    "toolkit",
    "ToolBox",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rs_box"
path = "src/lib.rs"


[dependencies]
lazy_static = "^1.4"
log = "^0.4"
log4rs = "^1.3"
toml = "^0.8"
